apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: eventrouter-template
  annotations:
    description: "A pod forwarding Kubernetes events to OpenShift Logging stack."
    tags: "events,EFK,logging,cluster-logging"
objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: eventrouter
      namespace: openshift-logging
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: event-reader
    rules:
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["get", "watch", "list"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: event-reader-binding
    subjects:
      - kind: ServiceAccount
        name: eventrouter
        namespace: openshift-logging
    roleRef:
      kind: ClusterRole
      name: event-reader
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: eventrouter
      namespace: openshift-logging
    data:
      config.json: |
        {
          "sink": "stdout"
        }
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: eventrouter
      namespace: openshift-logging
      labels:
        component: "eventrouter"
        logging-infra: "eventrouter"
        provider: "openshift"
    spec:
      selector:
        matchLabels:
          component: "eventrouter"
          logging-infra: "eventrouter"
          provider: "openshift"
      replicas: 1
      template:
        metadata:
          labels:
            component: "eventrouter"
            logging-infra: "eventrouter"
            provider: "openshift"
        spec:
          serviceAccount: eventrouter
          containers:
            - name: kube-eventrouter
              image: registry.redhat.io/openshift-logging/eventrouter-rhel8:v0.3
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/eventrouter
          volumes:
            - name: config-volume
              configMap:
                name: eventrouter
