apiVersion: v1
kind: Service
metadata:
    name: quickstart-es-http
    namespace: elasticsearch
spec:
    selector:
        app: quickstart-es
    ports:
        - protocol: TCP
            port: 9200
            targetPort: 9200
    type: NodePort
# prompt: make it simpiler for minikube